### ISSUE TITLE
漫画点击下一章后不会自动回到最上面

### ISSUE THREAD

**Issue by owen800q** [gavin66/reader-web#1]
如下图演示，点击下一章后，依然停留在最底部
![2148pm](https://user-images.githubusercontent.com/19252045/65814255-e709a080-e211-11e9-9205-fb06cb02c65a.gif)

**Comment by owen800q** [comment]
@gavin66

**Comment by gavin66** [comment]
@owen800q 移动端和 PC 端 scroolTop 的表现不一致, 你可以用手机的 safari 或 chrome 测试看

**Comment by owen800q** [comment]
手机确实没这个问题
